- .github/workflows/licensing.yml
- doc/dependency_decisions.yml
This adds standalone support for license scanning in this repo. It only has one dependency so there's not much to scan.
> actions: add LicenseFinder

- Makefile
- go.mod
This seems to have slipped into the go.mod while doing some testing against previous (gogo) implementations of features (such as size).
It is not needed by any package in this repo and makes its way into dependent modules. Removing this should be safe.
We can wait on https://github.com/planetscale/vtprotobuf/pull/29 to the rebase & see CI is green.
> Drop github.com/gogo/protobuf as it is unused

- .github/workflows/ci.yml
- Makefile
I had to build protobuf as this is the only way I found to obtain `conformance-test-runner`. This build is cached but first runs (for example any new pull request) will take a 30min-ish hit.
I can remove this time to zero by caching somewhere less temporary such as some Docker image in this repo's registry. What do you think?
While setting this up I noticed some generated files where out of sync with git. Should I add their diff to this PR?
<details>
<summary>Details</summary>
```diff
diff --git a/conformance/internal/conformance/conformance_vtproto.pb.go b/conformance/internal/conformance/conformance_vtproto.pb.go
index 980bbd5..8d6971f 100644
--- a/conformance/internal/conformance/conformance_vtproto.pb.go
+++ b/conformance/internal/conformance/conformance_vtproto.pb.go
@@ -89,19 +89,9 …
```
> Build and test in CI

- conformance/internal/conformance/conformance_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto2_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto3_vtproto.pb.go
- features/marshal/marshalto.go
* Once called before calling MarshalToVT
* Once called inside MarshalToVT
Also rename `marshalto` to `vtmsg` when checking for `MarshalToSizedBufferVT` to be consistent between oneof and embedded messages.
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>
> Avoid calling SizeVT two extra times for oneof fields

- README.md
In the README sample code, some of the import statements were spaces-indented, so I fix to tab.
> fix typo in README.md sample code

- README.md
- cmd/protoc-gen-go-vtproto/main.go
- conformance/internal/conformance/clonevt_test.go
- conformance/internal/conformance/conformance.pb.go
- conformance/internal/conformance/conformance_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto2.pb.go
- conformance/internal/conformance/test_messages_proto2_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto3.pb.go
- conformance/internal/conformance/test_messages_proto3_vtproto.pb.go
- features/clone/clone.go
- testproto/pool/pool_vtproto.pb.go
- testproto/pool/pool_with_slice_reuse_vtproto.pb.go
- testproto/proto2/scalars_vtproto.pb.go
- testproto/proto3opt/opt_vtproto.pb.go
This adds a new `clone` option to the generator that, when enabled, generates the following optimized methods for each message type:
- `func (p *YourProto) CloneVT() *YourProto`, which returns a cloned message, i.e., the resulting message is equal to `p` but does not share any memory.
- `func (p *YourProto) CloneGenericVT() proto.Message`, which does the same as the above, with the benefit of offering a type-independent signature such that it can be invoked via an interface type assertion on any `proto.Message` (in a dynamic setting where the type is not known at compile time, `CloneVT` can only be accessed via reflection/`MethodByName`)
Fixes #45. (actually, just one half, I can easily add the `CopyVT` logic if this is desired)
> clone: generate unrolled code for cloning messages

- conformance/internal/conformance/conformance_vtproto.pb.go
- conformance/internal/conformance/equalvt_test.go
- conformance/internal/conformance/test_messages_proto2_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto3_vtproto.pb.go
- features/equal/equal.go
Change the code generation to compare the actual types of oneof wrapper fields and ensure they are equal, rather than looking at the (potentially zero) values of the fields under the oneof (which could be either explicitly set or unset).
Fixes #50 .
> equal: fix bug confusing zero and unset oneof values

- conformance/internal/conformance/equalvt_test.go
- conformance/internal/conformance/test_messages_proto2_vtproto.pb.go
- features/equal/equal.go
- testproto/proto2/scalars_vtproto.pb.go
- testproto/proto3opt/opt_vtproto.pb.go
Updates the `equal` code generation to correctly generate presence checks for `bytes` fields where necessary, by distinguishing `[]byte(nil)` from `[]byte{}`. See #52 for a more detailed description.
Fixes #52 .
> equal: Generate presence checks for bytes fields, where necessary

- conformance/internal/conformance/clonevt_test.go
- conformance/internal/conformance/conformance_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto2_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto3_vtproto.pb.go
- features/clone/clone.go
- testproto/pool/pool_vtproto.pb.go
- testproto/pool/pool_with_slice_reuse_vtproto.pb.go
- testproto/proto2/scalars_vtproto.pb.go
- testproto/proto3opt/opt_vtproto.pb.go
The existing implementation of `CloneVT` was silently discarding unknown fields, breaking some basic assumptions (such that a clone should always be equal to the original). Thus, extend the test generation to also copy unknown fields.
Unit tests are included.
> clone: Take unknown fields into account

- README.md
Hello, 
So this adds instructions to add vtprotobuf to connect. 
connect-go uses the same interface as the grpc for `codec` and so it does work `grpc.Codec{}` but another alternative would be to copy the `grpc` directory to make a `connect` directory to decouple them.
Let me know what you think!
> Update README.md to add instructions to use with connect

- README.md
- conformance/internal/conformance/conformance_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto2_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto3_vtproto.pb.go
- features/clone/clone.go
- features/equal/equal.go
- testproto/pool/pool_vtproto.pb.go
- testproto/pool/pool_with_slice_reuse_vtproto.pb.go
- testproto/proto2/scalars_vtproto.pb.go
- testproto/proto3opt/opt_vtproto.pb.go
This PR adds a generator that makes `EqualVT` accessible with a uniform signature as `EqualMessageVT(proto.Message) bool`.
The main motivation is to ease migration from Gogo protobuf by offering a drop-in replacement for `"github.com/gogo/protobuf/proto".Equal`, which uses optimized code where available. With the change in this PR, this can simply be done via
```
func Equal(a, b proto.Message) bool {
if aVT, ok := a.(interface{ EqualMessageVT(proto.Message) bool }); ok {
return aVT.EqualMessageVT(b)
}
// we can disregard checking b because if a and b are not of the same type, Equal will be fast anyway
return proto.Equal(a, b) // from google.golang.org/protobuf/proto
}
```
I had added a similar facility when adding `CloneVT` via `CloneGenericVT`. However, with the launch of generics in …
> Add an EqualMessageVT generator

- .github/workflows/ci.yml
- features/marshal/marshalto.go
- features/size/size.go
- protobuf.sh
- testproto/proto3opt/opt_vtproto.pb.go
- testproto/proto3opt/proto3opt_test.go
Fixes https://github.com/planetscale/vtprotobuf/issues/65
The new optional semantics for Proto3 can be a bit tricky to get right. Bytes definitely need special handling.
> Fix handling of optional bytes in proto3

- README.md
Hi!
It was tricky to find out how to generate pools for messages. I think additional comments in README would help people.
It also closes #33
> Added details about generating pool methods to README

- features/pool/pool.go
- testproto/pool/pool_test.go
- testproto/pool/pool_with_slice_reuse_vtproto.pb.go
When using Pooling and so ResetVT we definitively want to reuse slices.
However a bug was recently discovered where it would not zeroed slice items. 
https://github.com/planetscale/vtprotobuf/pull/35 introduces a fixes by simply removing slice recycling which I think makes pooling a bit less interesting.
This PR rollback #35 and takes another approach that actually Reset the member even if ResetVT is not available because the feature pool is deactivate for that type.
I can't generate anything unfortunately I don't have the protoc version I'd appreciate help for re-generating those.
> Fixes missing Reset in ResetVT

- features/clone/clone.go
This PR adds support for using the vtpool when cloning poolable objects.
> feat: use vtpool when cloning poolable objects

- features/pool/pool.go
- testproto/pool/pool.pb.go
- testproto/pool/pool.proto
- testproto/pool/pool_test.go
- testproto/pool/pool_vtproto.pb.go
During `optional` fields internally represents as `oneof` ResetVT generates broken code for messages with `optional` messages.
Append checks on `field.Oneof.Desc.IsSynthetic()` to determine if field is real `oneof`
Closes #110
> fix: check oneof on syntetic

- conformance/internal/conformance/oneof_test.go
- conformance/internal/conformance/test_messages_proto2_vtproto.pb.go
- conformance/internal/conformance/test_messages_proto3_vtproto.pb.go
- features/marshal/marshalto.go
- features/size/size.go
- testproto/pool/pool_with_oneof_vtproto.pb.go
- testproto/unsafe/unsafe_vtproto.pb.go
- types/known/structpb/struct_vtproto.pb.go
Fixes https://github.com/planetscale/vtprotobuf/issues/61
This seems to pass all tests, but I am not super confident without https://github.com/planetscale/vtprotobuf/pull/129 passing
> Fix marshalling of empty oneOf messages

- README.md
The instructions for using vtprotobuf with Connect were incomplete - it is *required* to implement a custom gRPC-compatible codec a la Vitess because Connect internally uses the codec to directly serialize `Status` messages which do not have vtprotobuf helpers.
See https://github.com/connectrpc/connect-go/blob/main/protocol_grpc.go#L844-L846 and https://github.com/connectrpc/connect-go/blob/main/internal/gen/connectext/grpc/status/v1/status.pb.go
> Update README with custom codec needed for usage in Connect

- conformance/internal/conformance/oneof_test.go
- features/size/size.go
- testproto/pool/pool_with_oneof_vtproto.pb.go
- testproto/unsafe/unsafe_vtproto.pb.go
- types/known/structpb/struct_vtproto.pb.go
https://github.com/planetscale/vtprotobuf/pull/130 did not correctly account for the key size impacting the size. This fixes the original PR, and adds another test case to cover the issue
> Fix size on empty oneOf marshalling

- .github/workflows/ci.yml
https://github.com/planetscale/vtprotobuf/pull/140 requires >=1.23.0
> .github: bump Go version
